<pre class='metadata'>
Title: Single-Axis Scroll Containers
Shortname: single-axis-scroll-containers
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/single-axis-scroll-containers
URL: https://explainers-by-googlers.github.io/single-axis-scroll-containers
Editor: Free Debreuil, Google https://google.com, freedebreuil@google.com
Abstract: Extend CSS overflow to support single-axis scroll containers, with implications for `position: sticky` and DOM scroll APIs.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the <a href=[REPOSITORYURL]>explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
